### ISSUE TITLE
Why stop open sourcing PCB?

### ISSUE THREAD

**Issue by RigoLigoRLC** [monotech/NuXTv2#1]
For your sales or anything? Building one on your own isn't gonna be cheap either.

**Comment by monotech** [comment]
> For your sales or anything? Building one on your own isn't gonna be cheap either.

Hello

I will release the PCB layout file in the future, but I won't for the time being. I have no problems with individuals building themselves things, but there have been people popping up all over the world selling these things, completed or as kits, often of low quality or with the wrong parts, or rebranded. I'd like to make up for the months I've spent on the project at least, as it's more than a hobby for me.

Thanks :)

**Comment by RigoLigoRLC** [comment]
Thank you. Layout itself is also tedious, so I can understand what you're feeling.

**Comment by monotech** [comment]
I will likely release the PCB file after I produce the next batch soon.
