### ISSUE TITLE
some Questions about the design

### ISSUE THREAD

**Issue by ProxyPlayerHD** [monotech/NuXTv2#3]
Hi, i'm currently trying to design my own IBM PC XT compatible (but with CPLDs replacing a lot of discrete Logic ICs) using the NuXT and Micro 8088 as templates.

but there are some things that seem a bit confusing.

on the NuXTv2 Schematic:
U15 and U16 (A and B) just seem to be passing through some signals why exactly is that? are the signals too weak to run across the whole board?

next up, there are mutliple data busses that are seperated from eachother using tri-state bi-dir buffers. `AD0-7` is the Multiplexed Bus straight from the CPU, then there is `D0-7` which is the Demuxed Bus, and finally the `DB0-7` Bus.
Why exactly does the `DB` Bus exist? it connects to the RAM, IDE/CF Connector, and RTC. are any of thoe not able to let go of the Bus that they have to be shut off with an extra buffer?
if so, then why does the EEPROM (probably BIOS) connect to the normal `D` Bus, and the Flash ROM connects straigh to the CPU's `AD` Bus...?
and why an EEPROM in the first place? couldn't you fit the whole BIOS + XTIDE Extension inside a single SST39SF0x0A?

what sources did you use to figure out where to place the ISA Slots relative to the screw holes to allow for ISA Cards to be mounted in standard ATX Cases?

and lastly, about the ATX Power circuit, you're using an NE555 Timer to power on the PSU, but i was wondering if that couldn't just be done by a Microcontroller instead. (saving some space and components)
i'm planning on using an Atmega328p to do the Keyboard Translation and it has so many spare pins that i could use for other things, so my idea was to have it use the 5V Standby Power rail and monitor both the Reset and Power button, once you press Power it sends the `PS_ON` Signal to the PSU and waits for the `PWR_OK` signal, then it desserts the `RESET` Signal for the Motherboard. pressing the Reset button would just assert `RESET` for like a 0.5s. Pressing Power again after it's powered up just deasserts the `PS_ON` Signal.

in the end i don't know if that is a good idea. i looked online and never really found any project that used an Arduino or AVR to turn on a PSU.

and overall are there some quirks and things i should look out for when designing a PC XT like this?

i'm sorry if this is not really fitting to the rest of the questions, i was thinking you would have some experience with ATX Power-on circuits since you build atleast 2 at this point.

**Comment by monotech** [comment]
Heya. Not sure if this is the place for such. Perhaps emailing me would be better. Please send your reply to my email.

> U15 and U16 (A and B) just seem to be passing through some signals why exactly is that? are the signals too weak to run across the whole board?

Yes those ICs are used as bus buffers. Many analog considerations go into high speed digital signals, even if these aren't particularly high speed in the grand scheme of things.
Some things to think about:
- TTL logic, such as that found on most ISA cards, likes to draw current at its inputs. The more things on the Address or Data bus for example, the more current the ICs driving those buses must provide. CMOS inputs only draw a tiny leakage current.
- All inputs have some capacitance, as do the traces (the latter is tiny here). The traces have some resistance. The ICs driving the buses have a limited output current, so they can only bring the voltage at all the inputs on that bus to the desired level in a finite time (slew rate). ICs with weaker outputs can't operate as fast, and the square wave won't look very square and can cause problems. The ICs chosen have strong outputs.

> and why an EEPROM in the first place? couldn't you fit the whole BIOS + XTIDE Extension inside a single SST39SF0x0A?

I'm not sure what EEPROMs you are referring to.
The NuXT v1.2 has a ROM socket which can be used for any Option ROM or as an EEPROM writer. There are a lot of Option ROMs other than XT-IDE, and I intended it for tinkering purposes. It didn't get used much so was removed in the NuXT v2.0.

> Why exactly does the DB Bus exist? it connects to the RAM, IDE/CF Connector, and RTC. are any of thoe not able to let go of the Bus that they have to be shut off with an extra buffer?

Have a look at most old ISA cards, and you'll see the ICs on the card are behind their own Data bus through a 74LS245. This is beneficial when say, the ISA card had more than one input on the card loading the bus down. This drops that count to 1.
In the case of the DB bus on the NuXT v2.0, I put most of the onboard peripherals behind this, so the onboard bus buffer ICs have less to drive - hoping for greater compatibility with dodgy ISA cards here.
Note that some of the onboard peripherals, notably the 16C552, have weak outputs and must be behind a bus buffer if one wishes to fill the ISA slots with old TTL cards. If a peripheral isn't behind that bus buffer, it must drive all the ISA card inputs.

> what sources did you use to figure out where to place the ISA Slots relative to the screw holes to allow for ISA Cards to be mounted in standard ATX Cases?

Should be able to find such in Google images, or measure an existing board.

> and lastly, about the ATX Power circuit, you're using an NE555 Timer to power on the PSU, but i was wondering if that couldn't just be done by a Microcontroller instead. (saving some space and components)

That just wouldn't feel right. A whole computer with a CPU rivalling the 8088 just to handle the power button. Not to mention one more floating gate memory to go bad.

> i'm planning on using an Atmega328p to do the Keyboard Translation and it has so many spare pins that i could use for other things, so my idea was to have it use the 5V Standby Power rail and monitor both the Reset and Power button, once you press Power it sends the PS_ON Signal to the PSU and waits for the PWR_OK signal, then it desserts the RESET Signal for the Motherboard. pressing the Reset button would just assert RESET for like a 0.5s. Pressing Power again after it's powered up just deasserts the PS_ON Signal.

Now that is something I approve. My way of using two microcontrollers for the keyboard/mouse protocol converters is a result of my lack of software dev skills.
Personally, to simplify the design and reduce BoM, I would use one microcontroller to handle:
- power button
- AT to XT kbd
- PS/2 to serial mouse
- RTC (connect a much cheaper I2C RTC to the microcontroller. Make it compatible with DS12885 at port 70h as if a DS12885 were there, including the SRAM)

> and overall are there some quirks and things i should look out for when designing a PC XT like this?

The answer to that is yes, and I don't know them yet. You will find them in your prototyping and it'll be a good learning experience.

> i'm sorry if this is not really fitting to the rest of the questions, i was thinking you would have some experience with ATX Power-on circuits since you build atleast 2 at this point.

Read the relevant section in the ATX spec sheet. If I recall, the PS_ON signal is active-low with a 4.7k pull-up to 5VSB inside the PSU. So you can drive it with either an open-drain or push-pull output from the microcontroller powered by 5VSB.

> but with CPLDs replacing a lot of discrete Logic ICs

Some things about that:
- it's gonna cost a lot more
- it's likely less reliable, and less repairable if the files to program it are lost
- you will still need the bus buffers, so you aren't replacing that many ICs

Now if you implemented the whole XT chipset in an FPGA, that would be a winner.

Hope this helps!

**Comment by ProxyPlayerHD** [comment]
sorry but what exactly is your E-Mail address? i can't seem to find it....

**Comment by monotech** [comment]
> sorry but what exactly is your E-Mail address? i can't seem to find it....

Heya. Ask on the Monotech PCs site
